### ISSUE TITLE
analysis jobs marked as production

### ISSUE THREAD

**Issue by ddavila0** [dmwm/cms-htcondor-es#114]
I've notice there are some analysis jobs that are pushed as Type:production and trace this issue down to this part of the code:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L574

There are several analysis jobs, mostly jobUniverse 7 and 12, that do not have CRAB_Id neither define AccountingGroup and hence, they get marked as 'production', look at the condor query done on a crab schedd[1]

Wouldn't be better to use the CMSGWMS_Type attribute in the Schedd ClassAd to get the type of schedd (crabschedd, prodschedd, tier0schedd) and set the job Type respectively ?

[1]
[root@vocms0198 ~]# condor_q -const 'CRAB_Id=?=UNDEFINED' -af:h JobUniverse AccountingGroup | sort | uniq -c
    240 12          undefined            
     10 5           production.cmsdataops
      2 5           undefined            
      2 7           "highprio.spiga"     
   5242 7           undefined

**Comment by stiegerb** [comment]
@ddavila0 Are we sure there are only analysis jobs running on crabschedds and only production jobs running on the others? Afair there isn't a 1 to 1 correspondence there. @bbockelm?

For the jobs erroneously marked as 'production', is there a different way to tell them apart that we could implement?

**Comment by belforte** [comment]
CRAB schedd's run ony CRAB jobs.
But HammerCloud tests run on those schedd's in a different accounting group than analysis
to give priority. But HC has been discussed and proeprly labelled.

I see that you found jobs in universe 5 (vanilla = grid jobs) with accounting grou  production.cmsdataops. I will check what they are.

There are analysis jobs from non-crab schedd's though (MIT schedd, CMSConnect) where I have no way to label them. But we expect them to have the correct accounting group and fully
expect  that the code line pointed to by @ddavila0 works.

So, if a job does not have analysis accounting group, it should better be production, if not we have
some bug to track, not a design to change.

About jobuniverses 7 and 12, indeed there a thousands of such jobs in crab schedd's and they run locally on the schedd. The question is: do we want to list those ? or ignore ? If we want to list them, we need to define a proper naming and possibly add attributes so that they can be dealt with appropriately, I thought that you only collected jobs in universe 5. I am not against keeping track of jobs in local and schedd universe, actually I like it, and it may even help here and there. Simply we have to do the work to proprely identify and report them as the separate things that they are.

**Comment by ddavila0** [comment]
I would use the following table to decide the type of a particular job. On the y-axis we have the schedd type (prodschedd, crabschedd, etc) and in the x-axis the AccountingGroup (analysis, production, etc)

**CMSGWMS_Type/AccountingGroup | production | analysis | highprio | unknown**
**prodschedd** | production | unkown | production | production
**crabschedd** | unkown | analysis | analysis | analysis
**tier0schedd** | production | unkown | production | production
**institutionalschedd** | unkown | analysis | analysis | analysis
**cmsconnect** | unkown | analysis | analysis | analysis

**Comment by belforte** [comment]
We have already defined a procedure to assing TYPE to jobs listed in MONIT.
So I am not sure hat exact problem you want to solve here. THere are indeed odd jobs in the schedd queue e.g. in status Hold which are not "possible to fit", but.. do they really appear in MONIT ?
i.e. the 10 jobs in accounting group production.cmsdataops which you listed are these [1]
Also the 2 jobs with accounting group undefined are Held sleep jobs from Todor.
Do they appear in MONIT clouding the picture ? 
I'd rather spend as little time as possible on odd test jobs. May I simply remove them, or is there any use in keeping those sleep.sh around ? like investigating more ?

[1]
```
belforte@vocms0198/~> condor_q -const 'AccountingGroup=="production.cmsdataops"'
-- Schedd: crab3@vocms0198.cern.ch : <188.185.81.0:4080?... @ 05/07/19 20:09:44
 ID          OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
31636946.0   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.1   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.2   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.3   tivanov         3/21 12:10   0+00:00:01 H  0    0.0 sleep.sh 600
31636946.4   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.5   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.6   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.7   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.8   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
31636946.9   tivanov         3/21 12:10   0+00:00:00 H  0    0.0 sleep.sh 600
10 jobs; 0 completed, 0 removed, 0 idle, 0 running, 10 held, 0 suspended
belforte@vocms0198/~> 
```

**Comment by ddavila0** [comment]
The problem is that the crab jobs in Universe 12 are labeled in monit as "production". This happens because they do not have an AccountingGroup assigned to it and the code then decide they should be production jobs. We should either assign these jobs the "analysis" AccountingGroup so that the current code classifies them correctly or we make the code smarter to not assign all "unknown" AccountingGroups to "production" but better classify unkown AccountingGroups based on  the type of schedd they come from

**Comment by belforte** [comment]
Let's fix it in crab side then! sent from Stefano's mobileOn May 7, 2019 14:48, ddavila0 <notifications@github.com> wrote:The problem is that the crab jobs in Universe 12 are labeled in monit as "production". This happens because they do not have an AccountingGroup assigned to it and the code then decide they should be production jobs. We should either assign these jobs the "analysis" AccountingGroup so that the current code classifies them correctly or we make the code smarter to not assign all "unknown" AccountingGroups to "production" but better classify unkown AccountingGroups based on  the type of schedd they come from

**Comment by ddavila0** [comment]
I agree, fixing on CRAB side makes more sense and will fix most of the wrong classification but I still think that the code could be improved, I would at least add an extra "if" to check if the AccountigGroup starts with "production" and if not, then mark the jobs as "unknown"

**Comment by stiegerb** [comment]
I would suggest to wait until you fix the issue on the CRAB side (i.e. until some or most of these jobs without AccountingGroup are correctly classified). Afterwards we can better tell what's left to deal with.

**Comment by belforte** [comment]
Agreed. So I have increased CRAB side issue priority and will try to get it done this week.

**Comment by belforte** [comment]
As I set to do this in CRAB, I think that simply the code in htcondor-es has not kept up with design.
We agreed that Type is not heuristically defined based on Crab_Id or similar like in
https://github.com/dmwm/cms-htcondor-es/blob/37d55e9758a4f800146d1a86702f97c7c771bccb/src/htcondor_es/convert_to_json.py#L575-L583
But is set via the CMS_Type attributes in the classAds by WMA and/or CRAB, see e.g.
https://docs.google.com/spreadsheets/d/1x73SxboZqNvpYKHmaJ9PioT3itpw4qQrTjUecnKLTi4/edit#gid=0
CRAB already complies with that for grid jobs.
So I will simply make sure that same classAds are also set for jobs in scheduler and local universe,
leaving alone accountiongGroup which does not belong there and would be only confusing.
Namely I will set:
* `CMS_WMTool`:  USER or HammerCloud
* `CMS_SubmissionTool`: CRAB
* `CMS_Type`: Analysis or Test (for HammerCloud)
* `CMS_TaskType`:  Script or cmsRun or kind of test activity for HC
I guess you want to open an issue for making the report to use the final classAds nomenclature defined last winter, and I would like also to have those available in the dashboard (they are supposed to be influxDB indexes already IIUC).

**Comment by belforte** [comment]
Done. WIll do a quick test in preprod and will go in production with next update.

**Comment by stiegerb** [comment]
Ok, we'll need to:
- Update the `Type` definition you linked to
- Add those new fields as tags in influxdb (i.e. open a ticket with MONIT to do it)
- Add those new tags as selectable options in the job monitoring dashboard

**Comment by amaltaro** [comment]
@belforte has this fix been pushed to production? I still see CRAB3 schedds when filtering `production` jobs in the job monitoring.

I might be wrong, but I think Benjamin has already left CMS, so you'd need to get in touch with Christian (CMS Monitoring person).

**Comment by belforte** [comment]
@amaltaro it was tagged in last release which Leo deployed in production this morning https://github.com/dmwm/CRABServer/releases/tag/3.3.1906.rc3
It will take up to one month before old tasks w/o the fix disappear from the sytem.
But this should only affect jobs in scheduler or local universe, do we have no other way to filter them out ?  I think it is bad to mix jobs from those universes with those from vanilla universe in the same dashboard, even if labelled as CRAB.
Doi we still suffer of lack of design clarity ?

**Comment by amaltaro** [comment]
Ok, thanks Stefano.

About your design comment, we had many discussions about job monitoring when conceiving this and the job universe never came up in any of those, AFAIR. We discussed generic types (analysis, production, etc) and the task type (which tries to characterize the process itself).
Anyways, I'm pretty sure your comment/question wasn't made to me.

**Comment by belforte** [comment]
You are fully correct Alan. 
For a long time I was thinking that other universes were simply ignored, since the scope always seemed to be "monitor grid jobs", so I did not raise the issue. Now we found that those universes are not. So we have to make  high level decisions (in architecture, not politics)  about how to handle those to avoid ad-hoc `if this if that`, here and there in the code.

**Comment by leggerf** [comment]
No idea what universes are. But we should take up again the discussion and implementation of new (by now old) monitoring attributes, especially in view of the WMA release mid July. 


-------- Messaggio originale --------
Da: Stefano Belforte <notifications@github.com> 
Data: 2019/06/07  17:24  (GMT+01:00) 
A: dmwm/cms-htcondor-es <cms-htcondor-es@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Oggetto: Re: [dmwm/cms-htcondor-es] analysis jobs marked as production (#114) 

You are fully correct Alan.
For a long time I was thinking that other universes were simply ignored, since the scope always seemed to be "monitor grid jobs", so I did not raise the issue. Now we found that those universes are not. So we have to make high level decisions (in architecture, not politics) about how to handle those to avoid ad-hoc if this if that, here and there in the code.

**Comment by belforte** [comment]
https://htcondor.readthedocs.io/en/v8_8_3/users-manual/running-a-job-steps.html

**Comment by amaltaro** [comment]
Apologies for not reading the whole discussion, but I understand that if a job class ad doesn't define a type, then the job monitoring script consuming the classads assume it's a `production` job. If that's correct (?), I think the first change would be to remove such default, since ALL production jobs must contain a type value.

**Comment by belforte** [comment]
About universes: summary of our use cases:
* vanilla universe = global glideinWMS pool aka "grid jobs" WMA only uses that, so far.
* scheduler and local universe can run scripts on the "submission machine" and are used by CRAB to exploit condor DAGMAN. (no special good reason not to use only one of the two,
a choice by developers at the time which I never liked).

About default type: agree with Alan, default should be unknown

**Comment by leggerf** [comment]
assigning to @cronosnull 
Regarding universes, I made  a note about them when we'll finally get back to discuss new classAds https://its.cern.ch/jira/browse/CMSMONIT-84

**Comment by cronosnull** [comment]
If I understood correctly, jobs must include the CMS_Type classAd in order to implement this change in the script (currently seems that production jobs and some analysis jobs don't include it). 
![image](https://user-images.githubusercontent.com/4405564/59261177-4466eb00-8c3d-11e9-8c76-33a1af788e12.png)
Once it is send I'll change the script to set the type based on that attribute (eventually we should change the dashboards and the mappings that use it to use the CMS_Type field, in order to avoid duplicate information).

**Comment by leggerf** [comment]
@cronosnull can't we just fix the default? Just set it to unknown, and then it will be up to the upstream data producers (CRAB,WMA) to fill in job Type correctly

**Comment by cronosnull** [comment]
I just created the pull request (#129), but once merged we will have all production non-analysis jobs marked as unknown until the producers send the CMS_Type correctly. 
@belforte, @amaltaro, @leggerf  could you review it?
