### ISSUE TITLE
Repeated records when a jobs is removed.

### ISSUE THREAD

**Issue by ddavila0** [dmwm/cms-htcondor-es#141]
It seems that when a job gets removed, the monitoring system keeps adding duplicate records of it every 12 minutes. In this example:
https://monit-kibana.cern.ch/kibana/app/kibana::/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-29T22:00:00.000Z',mode:absolute,to:'2019-08-07T21:59:59.999Z'))&_a=(columns:!(_source),index:'monit_prod_condor_raw_metric_v002-*',interval:auto,query:(query_string:(query:'data.CRAB_Retry:3+AND+data.CRAB_Id:11+AND+data.CRAB_Workflow:190702_095101*acarvalh_crab_2016v3_2019Jul02_ZZTo2L2Nu_13TeV_powheg_pythia8__RunIISummer16MiniAODv3-PUMoriond17_94X_mcotic_v3-v2')),sort:!(metadata.timestamp,desc))

you can see that all of the records point to the exact same job, same LastStartTime, same globalJobId, etc. One thing to notice is that the CpuEff does change. This could be the reason why the monitoring system thinks it is a different record. I think this is related to this bug in condor:https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=7083

**Comment by cronosnull** [comment]
Diego, I only see one report with the status Removed, the other documents were sent when the job was running and idle (I added the filter by the state to your query in [1])

[1] https://monit-kibana.cern.ch/kibana/goto/c57b75330474f32cfce2d54574a1c065. 

If you are querying for analysis jobs you can use the monit_prod_condor_raw_tasks index which only has one document per GlobalJobId (the last report), but it only has a subset of the fields (and uses the task creation date as the timestamp, so you will need to change the filter).

**Comment by cronosnull** [comment]
@ddavila0, I will close this issue but no doubt in reopening if you have any question or I missed something.

**Comment by ddavila0** [comment]
Hi Christian, sorry to reply until now. 
I was looking at the quick count of JobStatus (not Status) and got surprised to see 100% with value '3' which means 'Removed', but now I see that is because JobStatus is only reported when the job gets removed (which is confusing/wrong).

On the other hand, I was looking at the HDFS data of the classAds and I do see duplicates on jobs in there. Look at this[1] swan notebook where I get 5 records for the same job with Status==Removed. Here is the same query on Kibana[2] with no duplicates.

[1]https://cernbox.cern.ch/index.php/s/Ia2oO5hPlGGkVJB
[2]https://monit-kibana.cern.ch/kibana/goto/000d2da1f3e14ccc086bcf88d72a41c9

**Comment by cronosnull** [comment]
Hi Diego, 

Yes, for the running jobs we only send a subset of the fields[1], and it doesn't include JobStatus (I guess is because the status encodes the same data). 

In hdfs you see all the messages sent, so you will see a lot of repeated messages there. In elastic search we use the document id to avoid duplicates, in the raw index it is the globalJobId+recordtime (and the record time is, for completed jobs, the EnteredCurrentStatus or the completion date, avoiding most of the duplicates -you can still see two records for completed jobs[2]).  If you want to use spark, you can use the globaljobid, take the rows with the max record time and, then, drop duplicates. 

[1] https://github.com/dmwm/cms-htcondor-es/blob/7d1547828a0dfa63305e8deb714be20e112642f2/src/htcondor_es/convert_to_json.py#L429
[2] https://cernbox.cern.ch/index.php/s/Q890H4ACm67W9AX  The change was deployed in February, so if you query for older data you will have a lot of repeated records.

**Comment by ddavila0** [comment]
Ok, thank you for the explanation!

Cheers,

Diego
