### ISSUE TITLE
commonExitCode defaults to 0 (meaning "sucess") when no classad is available to provide the exitCode of the job

### ISSUE THREAD

**Issue by khurtado** [dmwm/cms-htcondor-es#208]
When looking into the following grafana dashboard:
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring?orgId=11

we realized we had some jobs that were "Removed" but the exit code was successful. When investigating this, we noticed the following line:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L1157

basically means when a job is removed and hence neither CRAB, WMCore or HTCondor gets to propagate a classad to report a exit code, it defaults to "0".

This shouldn't be the case, but we are wondering what the value should be instead. After discussing his, we came up with some options and we wanted to hear feedback from the monitoring team;

Options are: 
 - "Unknown": While this is possible, we don't know how LUCENE will treat it if we try conditionals like "ExitCode > 0"
 - ` -1` : Only issue with this is, exit codes are usually positive
 - A positive integer number > 99999 ? E.g.: 100001
Because it's past the range used for CMS exit codes and it means it wasn't produced by [WMException](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py), although it's not easy for someone to say so without looking at the documentation/WMException comments.	https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes
On the other hand, it does fit the "ExitCode>0 == failed job" concept, as opposed to the "-1".

Do you have any comments on what the best exit code to default should be (one that does have side effects with monitoring)

Related issues:
https://github.com/dmwm/WMCore/issues/11614

**Comment by leggerf** [comment]
Thanks for your feedback.
I think the less disruptive is to have option 3: A positive integer number > 99999 ? E.g.: 100001

@nikodemas can you pls open an internal jira ticket to us with this request?

**Comment by belforte** [comment]
I agree that none of "undefine/-1/100001" is appealing.

what about
```
50669 - Application terminated by wrapper for not defined reason 
```
it is true that it was not exactly the wrapper, but in a way... condor_rm signals the job, the wrapper traps it and exit.


I have not digged in details, but it is also possible for jobs to be removed while idle, before any wrapper started.
If we prefer a general solution I propose to add the apocalyptic :
```
50666 - Job killed by condor for unknwon reasons
```

**Comment by belforte** [comment]
and of course, in due time, we will try to report a reason for those jobs, in case we can. It is not super-elegant to have an exit code explicitely about condor, but should we ever go for a different scheduler, this will be a drop in the ocean of changes.

**Comment by amaltaro** [comment]
> 50666 - Job killed by condor for unknwon reasons

This exit code is still free in the WM exceptions module: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py and I would be happy to incorporate it there. However, perhaps we could rephrase the error message to something like: `50666 - Job removed by condor for unknown reasons`, just so we have the "removed" association :-)

**Comment by belforte** [comment]
thanks for the refinement Alan. I have added to [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes) I leave it to you and Kenyi to take care of [WMExceptions](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py). We should also let Valentin know when he's back, in case [ExitCodes](https://cmsweb.cern.ch/exitcodes/) does not pick this up automatically

**Comment by belforte** [comment]
if consensus is not reached, it will be easy to roll back teh Twiki

**Comment by khurtado** [comment]
+1 for 50666. Since CRAB and WMCore agrees on it, I made a PR. Just waiting for monit to agree to it as well.

**Comment by amaltaro** [comment]
@khurtado can you please also create a PR for WMCore (for the WMExceptions)? Such that it will close the issue https://github.com/dmwm/WMCore/issues/11614

**Comment by leggerf** [comment]
all good for monitoring. Way better to have this fixed upstream.

**Comment by leggerf** [comment]
just to confirm, @khurtado you'll fix this upstream so that we do not have to merge #209 ?

**Comment by belforte** [comment]
@leggerf there's a misunderstanding here. This can't be fixed upstream. The problem is jobs removed by condor without CRAB/WMA having chance to report anything. FIx has to be done in the spider .
In any case it is not good that spider has exit_code=0 as default.
Default should always be "fail", and "good" flag only set when we have confirmed that everything is good.

The discussion here was only about which exit code to use for that situation.

Whether we can improve wrappers, or condor schedulers to reduce the number of jobs where this 50666 "default" has to be applied, and wheter we may ever be able to make that 0, is a different story. Of course we should set different exit codes in case, since then there will be a known reason. Problem is difficult (we already do our best here), needs ad hoc investigation, i.e. time. I do not expect progress unless the fraction of 50666 becomes significant.

Hope everybody agrees and everything is clear !

**Comment by leggerf** [comment]
tnx for clarifying, then @nikodemas will merge and deploy the PR

**Comment by nikodemas** [comment]
I have deployed the changes.

However, I am not sure that it made the difference we were aiming for (see [dashboard](https://es-cms.cern.ch/dashboards/goto/a405f800240a95cda8988f82bb1bbfd2?security_tenant=global)). The issue is that the `JobFailed` field is derived before the `ExitCode` derivation (see [code](https://github.com/dmwm/cms-htcondor-es/blob/48a92c556ec769b1de8e6cc9ea6882006e971fc9/src/htcondor_es/convert_to_json.py#L666)) that @khurtado just fixed, so `JobFailed` still doesn't show any failures.

I could simply move `commonExitCode(ad)` before the `JobFailed` derivation and use `result` as an input variable instead of `ad` for it, but please confirm that my understanding is correct.

**Comment by khurtado** [comment]
@nikodemas Ahhh, good catch. Yes, it seems `ExitCode` is now defaulting to the new value but `JobFailed` needs to follow a similar logic to be consistent with `commonExitCode`. My vote would be to make `JobFailed` to depend on `commonExitCode`

E.g.: change [this code](https://github.com/dmwm/cms-htcondor-es/blob/48a92c556ec769b1de8e6cc9ea6882006e971fc9/src/htcondor_es/convert_to_json.py#L1132-L1141) so that it just says something like:

```
if commonExitCode(ad) > 0:
    return 1
else:
    return 0    
```

@belforte Would the above work for CRAB?
@amaltaro The problem with the above for production would be that for `commonExitCode`, we are using only `Chirp_WMCore_cmsRun_ExitCode`, but for `JobFailed` I see there is 3:

```
        "Chirp_WMCore_cmsRun_ExitCode",
        "Chirp_WMCore_cmsRun1_ExitCode",
        "Chirp_WMCore_cmsRun2_ExitCode",
```

Do you know if we need all 3 of them, or is the first enough? And if we need all 3 of them, is that all we need or should we go all the way go cmsRun3, cmsRun4, etc?

**Comment by amaltaro** [comment]
> Do you know if we need all 3 of them, or is the first enough? And if we need all 3 of them, is that all we need or should we go all the way go cmsRun3, cmsRun4, etc? 

I would be in favor of completely removing those cmsRunX exit code and rely solely on the `Chirp_WMCore_cmsRun_ExitCode` (or ExitCode for jobs that don't run CMSSW).
