### ISSUE TITLE
CMSPrimaryProcessedDataset and CMSPrimaryPrimaryDataset not present in some ES indexes

### ISSUE THREAD

**Issue by khurtado** [dmwm/cms-htcondor-es#211]
Hello,

While looking into the following issue:
https://github.com/dmwm/WMCore/issues/11613

It was found out that some [indexes](https://monit-opensearch.cern.ch/dashboards/app/discover?security_tenant=global#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(data.CMSPrimaryPrimaryDataset,data.CMSPrimaryDataTier,data.CMSPrimaryProcessedDataset,data.DESIRED_CMSDataset),filters:!(),index:dd1ba850-d169-11ea-966a-e1c0a7950cea,interval:auto,query:(language:kuery,query:'data.WMAgent_RequestName:pdmvserv_Run2022C_EGamma_27Jun2023_230627_115909_2933'),sort:!())) like the one used for `monit_prod_condor` seem to be missing some entries from this block:

https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L751-L757

Basically, if we have something like (as shown in the ES link above):
```
data.DESIRED_CMSDataset : /EGamma/Run2022C-v1/RAW
```
Then, we should see:
data.CMSPrimaryPrimaryDataset,  data.CMSPrimaryDataTier,  data.CMSPrimaryProcessedDataset
but only `data.CMSPrimaryDataTier` is properly shown, with the other 2 set as `Unknown`. I haven't see this in other indexes like `cms-20*`, is this a bug?

Also, we had a few questions regarding the names:

- CMSPrimaryPrimaryDataset:  why Primary twice in the name?
- CMSPrimaryDataTier, would it be better to rename it to DESIRED_CMSDatatier? In such case, we would like to do some renaming to make things clearer, like:

- CMSPrimaryPrimaryDataset -> DESIRED_CMSPrimaryDataset
- CMSPrimaryProcessedDataset -> DESIRED_CMSProcessedDataset
- CMSPrimaryDataTier -> DESIRED_CMSDatatier

what do you think?
pinging @amaltaro

**Comment by nikodemas** [comment]
Hi @khurtado,

the fields you mentioned are not there because the `Status` of these records is in `Running`, `Idle` or `Held`. You can see the function dropping the fields [here](https://github.com/dmwm/cms-htcondor-es/blob/48a92c556ec769b1de8e6cc9ea6882006e971fc9/src/htcondor_es/convert_to_json.py#L1426) and the list of fields that are kept for the records with these statuses [here](https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L441-L540). I do not know what was the reason (maybe to save storage because `Idle` and `Running` jobs are in majority) for dropping some fields for the running jobs, but if you think that it is needed we can keep the `CMSPrimaryPrimaryDataset` and `CMSPrimaryProcessedDataset` (or any other fields that you might need in the future) for the running jobs as well. `cms-20*` index has only `Completed` jobs, therefore these fields are always filled there.

Regarding the renaming - it might cause some confusion in the indexes for historical data because then we would have two fields for the same information, so my advice would be not to do it :D However, if you think that it is still necessary I can ask my team or even MONIT what should be the approach here.

**Comment by khurtado** [comment]
@nikodemas Thank you for the explanation! That makes sense. Pinging @amaltaro: after reading nikodemas response, do you think we should request these other 2 fields to be populated at running time, or should we stick with those only for completed jobs? See the above regarding renaming as well.

**Comment by amaltaro** [comment]
Thank you for these details, Nikos.
Yes, I don't think it is important to break down the dataset name (primary dataset, processed dataset, datatier) for running jobs. The most important is indeed for completed jobs.

Regarding the naming, I agree it's not a trivial change and we are happy with any decision. It was worth though pointing out that the naming - at least IMO - could be misleading as is.

**Comment by nikodemas** [comment]
Thank you for your comments.
I will ask my team and MONIT about the naming next week during a meeting and will let you know what are their thoughts on this.

**Comment by nikodemas** [comment]
I have just realized that I didn't get back to you regarding this. I have talked to MONIT and as we have guessed they wouldn't like to do any renaming. Since you have mentioned that you are fine with not having the names changed, I am closing this issue.

Feel free to reopen issue if needed.
