### ISSUE TITLE
Elasticsearch 5 Migration

### ISSUE THREAD

**Issue by stiegerb** [dmwm/cms-htcondor-es#5]
I'll collect here some issues that appear.

- Need to change the type of (some or all?) string fields from `text` to `keyword` in the mappings for them to be used in aggregations. See [here](https://discuss.elastic.co/t/cant-see-all-fields-when-visualize-aggregation-terms-is-selected-in-kibana/78010)

**Comment by stiegerb** [comment]
Analyzers for `keyword` mapped fields are not supported, see [here](https://github.com/elastic/elasticsearch/issues/18064).

**Comment by bbockelm** [comment]
Hi Benjamin,

Is there a PR for this yet?

Brian

**Comment by stiegerb** [comment]
Not yet. I'll make one first thing Monday.
Do you want to keep ES5 and ES2 developments separate?

Benjamin

**Comment by bbockelm** [comment]
Ok, merged!

Should we wait to see if there are further issues - or do you want to give Ulrich the go-ahead for an upgrade?

**Comment by stiegerb** [comment]
Let me have another look tomorrow before we do the upgrade.

**Comment by bbockelm** [comment]
@stiegerb --- migration is done.  I did have to partially revert some of your changes.

Particularly, the change from `epoch_second` to `epoch_millis` did not go smoothly because new records have to be uploaded for existing indices.

We should be able to re-introduce them by having a flag date: any records uploaded in an index after day XYZ should use the format; older records utilize the old format.

Can you look into this when you get back?

**Comment by stiegerb** [comment]
Hi Brian,
In fact I'm not sure we need to do that change at all now. I did this originally because the CERN Monit elasticsearch instance wants all timestamps in milliseconds. So to have our Recordtime accepted as a timestamp they asked me to change the format. But then in the end they never got to changing the index so nothing actually happened. For our own instance, we can just keep the format as second anyway.

**Comment by bbockelm** [comment]
This was all done awhile back - closing!
